### ISSUE TITLE
Motstridende råd om tidspunkt for scanning av Docker images?

### ISSUE THREAD

**Issue by ahusby** [navikt/security-playbook#151]
[Her](https://sikkerhet.nav.no/docs/goldenpath/) står det 

> Kjør slike scans regelmessig selv om du ikke har gjort endringer i appen din, det kan ha dukket opp nye problemer siden sist. Dette gjøres ved å legge til en scheduled trigger på workflowen.

mens [her](https://sikkerhet.nav.no/docs/verktoy/trivy) står det 

> Legg til aquasecurity/trivy-action i din workflow etter stegene der du bygger Docker-imaget:

Er ikke det motstridende eller selvmotsigende? Dvs. slik jeg leser det beskriver den siste lenken en løsning for scan ved deploy av en endring av applikasjonen, mens den første lenken sier at scan bør skje regelmessig selv om man ikke har endret appen.

**Comment by albrektsson** [comment]
Beror vel på når du bygger ditt image? Eksemplet på trivy-lenken sier inget om når du kjører din workflow.. pipelines håndteres jo på forskjellige måter i teamene så her tenker jag att man får sette det opp som man vill ha det selv.

Om du setter opp workflowet med on push to main og ditt team pusher kode til main 20 ggr per dag, året runt, så får du kanskje ikke ut så mye av å bruke schedule i tillegg... Men om du har en applikasjon som gjerne ligger stille i flere uker kan det vara lurt å ha scanning på schedule :)

My 2c iallefall :D

**Comment by perchrnie** [comment]
Vi ønsker at man skal gjøre begge deler, så nå har jeg oppdatert begge sider slik at det forhåpentligvis blir tydeligere. Tror at dette løser denne 🤞
