### ISSUE TITLE
Død lenke i dokumentasjon

### ISSUE THREAD

**Issue by ahusby** [navikt/security-playbook#20]
Død lenke i "finner du her" på https://github.com/navikt/security-playbook/blob/main/docs/07-sikker-utvikling/tilgangsstyring.md

> I NAV har vi valgt å ta i bruk [OAuth 2.0](https://oauth.net/2/) og [OpenID Connect (OIDC)](https://openid.net/connect/) for dette formålet. En introduksjon til disse samt tilhørende begrep og uttrykk finner du [her](https://nais.io/blog/posts/2020/09/oauth1).

og i 
> mens for ID-porten har vi laget et tilsvarende opplegg som vi har kalt TokenX. Mer info finnes på [NAIS-bloggen](https://nais.io/blog/posts/2020/09/oauth2).

**Comment by jksolbakken** [comment]
Fikset i [4eb6c3e](https://github.com/navikt/security-playbook/commit/4eb6c3ec996601894447cac5f934491ede7fea31)
