### ISSUE TITLE
Oppgradere Amplitude klient til @amplitude/analytics-browser

### ISSUE THREAD

**Issue by eilifjohansen** [navikt/security-playbook#205]
[amplitude-js](https://github.com/amplitude/Amplitude-JavaScript) pakken blir ikke lenger aktivt vedlikeholdt. 

Amplitude har laget en ny pakke [@amplitude/analytics-browser](https://www.npmjs.com/package/@amplitude/analytics-browser) som de nå satser på. Den nye pakken bygger på Typescript, og er ifølge Amplitude mer utviklervennlig ++

Det kan være ulike risikoer knyttet til å benytte pakker som ikke vedlikeholdes aktivt. En anbefaling er derfor å bytte over til den nye pakken :package:

**Comment by jksolbakken** [comment]
Done!
